# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Theme
theme: minimal-mistakes-jekyll

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Learning with Machines
# Use > for folding and - for chomping
description: >-
  Jeffrey Dick | Data Scientist | Portfolio and Blog
search: true
locale: en-US
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: CN

# Permalinks and navigation
permalink: /:categories/:title/
breadcrumbs: true

# Directories to include and exclude from processing
include:
  - _pages
exclude:
  - work

# Analytics
head_scripts:
  - /assets/js/matomo.js

# Personalization
author:
  name: Jeffrey Dick
  avatar: /assets/siteimages/bio-photo.jpg

# Customization
defaults:
  # All posts and pages
  - values:
      layout: single
      classes: wide
      author_profile: true
      sidebar:
        nav:
          - AI
          - science
  # Posts
  - scope:
      type: posts
    values:
      show_date: true
      read_time: true
      share: true
      related: true

tag_archive:
  type: liquid
  path: /tags/
